services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./.data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0
    restart: unless-stopped